name: faculty_project
description: HUCI faculty project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  barcode_widget: ^2.0.2
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_translate: any
  fluttertoast: any
  font_awesome_flutter: ^9.2.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.2.2

flutter_localizations:
  sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/i18n/
  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_wght.ttf
    - family: tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
