///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BannersModelBanners {
/*
{
  "id": 1,
  "type": "main",
  "link": "https://www.youtube.com/watch?v=0yOqxzl-4DI",
  "image": "assets/images/banners/test.jpg"
}
*/

  int? id;
  String? type;
  String? link;
  String? image;

  BannersModelBanners({
    this.id,
    this.type,
    this.link,
    this.image,
  });

  BannersModelBanners.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    type = json['type']?.toString();
    link = json['link']?.toString();
    image = json['image']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['type'] = type;
    data['link'] = link;
    data['image'] = image;
    return data;
  }
}

class BannersModel {
/*
{
  "status": 200,
  "errorNum": "S000",
  "message": "Banners has been returned successfully",
  "banners": [
    {
      "id": 1,
      "type": "main",
      "link": "https://www.youtube.com/watch?v=0yOqxzl-4DI",
      "image": "assets/images/banners/test.jpg"
    }
  ]
}
*/

  int? status;
  String? errorNum;
  String? message;
  List<BannersModelBanners?>? banners;

  BannersModel({
    this.status,
    this.errorNum,
    this.message,
    this.banners,
  });

  BannersModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    errorNum = json['errorNum']?.toString();
    message = json['message']?.toString();
    if (json['banners'] != null) {
      final v = json['banners'];
      final arr0 = <BannersModelBanners>[];
      v.forEach((v) {
        arr0.add(BannersModelBanners.fromJson(v));
      });
      banners = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['errorNum'] = errorNum;
    data['message'] = message;
    if (banners != null) {
      final v = banners;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['banners'] = arr0;
    }
    return data;
  }
}
