///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CourseSubscriptionsModelSubscriptions {
/*
{
  "id": 1,
  "sessions_number": 8,
  "validated_weeks": 7,
  "price": 54
}
*/

  int? id;
  int? sessionsNumber;
  int? validatedWeeks;
  int? price;

  CourseSubscriptionsModelSubscriptions({
    this.id,
    this.sessionsNumber,
    this.validatedWeeks,
    this.price,
  });
  CourseSubscriptionsModelSubscriptions.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    sessionsNumber = json['sessions_number']?.toInt();
    validatedWeeks = json['validated_weeks']?.toInt();
    price = json['price']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['sessions_number'] = sessionsNumber;
    data['validated_weeks'] = validatedWeeks;
    data['price'] = price;
    return data;
  }
}

class CourseSubscriptionsModel {
/*
{
  "status": 200,
  "errorNum": "S000",
  "message": "Course Subscriptions has been returned successfully",
  "subscriptions": [
    {
      "id": 1,
      "sessions_number": 8,
      "validated_weeks": 7,
      "price": 54
    }
  ]
}
*/

  int? status;
  String? errorNum;
  String? message;
  List<CourseSubscriptionsModelSubscriptions?>? subscriptions;

  CourseSubscriptionsModel({
    this.status,
    this.errorNum,
    this.message,
    this.subscriptions,
  });
  CourseSubscriptionsModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    errorNum = json['errorNum']?.toString();
    message = json['message']?.toString();
    if (json['subscriptions'] != null) {
      final v = json['subscriptions'];
      final arr0 = <CourseSubscriptionsModelSubscriptions>[];
      v.forEach((v) {
        arr0.add(CourseSubscriptionsModelSubscriptions.fromJson(v));
      });
      subscriptions = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['errorNum'] = errorNum;
    data['message'] = message;
    if (subscriptions != null) {
      final v = subscriptions;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['subscriptions'] = arr0;
    }
    return data;
  }
}
