///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CoursesModelCourses {
/*
{
  "id": 1,
  "title": "مادة الرياضيات",
  "intro_video": "https://youtu.be/NsEReUrQoao?list=PLoXcfNwaVZDYuQ-rcKE9yXZL1O2vzUEt0",
  "thumbnail": "assets/images/courses/math-thumbnail.jpg",
  "annual_price": 500,
  "image": "assets/images/courses/math.jpg",
  "tags": [
    "اللغة العربية"
  ],
  "level_id": 1,
  "is_enrolled": true,
  "level_title": "الصف الاول الاعدادي"
}
*/

  int? id;
  String? title;
  String? introVideo;
  String? thumbnail;
  int? annualPrice;
  String? image;
  List<String?>? tags;
  int? levelId;
  bool? isEnrolled;
  String? levelTitle;

  CoursesModelCourses({
    this.id,
    this.title,
    this.introVideo,
    this.thumbnail,
    this.annualPrice,
    this.image,
    this.tags,
    this.levelId,
    this.isEnrolled,
    this.levelTitle,
  });
  CoursesModelCourses.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    introVideo = json['intro_video']?.toString();
    thumbnail = json['thumbnail']?.toString();
    annualPrice = json['annual_price']?.toInt();
    image = json['image']?.toString();
    if (json['tags'] != null) {
      final v = json['tags'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      tags = arr0;
    }
    levelId = json['level_id']?.toInt();
    isEnrolled = json['is_enrolled'];
    levelTitle = json['level_title']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['intro_video'] = introVideo;
    data['thumbnail'] = thumbnail;
    data['annual_price'] = annualPrice;
    data['image'] = image;
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['tags'] = arr0;
    }
    data['level_id'] = levelId;
    data['is_enrolled'] = isEnrolled;
    data['level_title'] = levelTitle;
    return data;
  }
}

class CoursesModel {
/*
{
  "status": 200,
  "errorNum": "S000",
  "message": "Courses has been returned successfully",
  "courses": [
    {
      "id": 1,
      "title": "مادة الرياضيات",
      "intro_video": "https://youtu.be/NsEReUrQoao?list=PLoXcfNwaVZDYuQ-rcKE9yXZL1O2vzUEt0",
      "thumbnail": "assets/images/courses/math-thumbnail.jpg",
      "annual_price": 500,
      "image": "assets/images/courses/math.jpg",
      "tags": [
        "اللغة العربية"
      ],
      "level_id": 1,
      "is_enrolled": true,
      "level_title": "الصف الاول الاعدادي"
    }
  ]
}
*/

  int? status;
  String? errorNum;
  String? message;
  List<CoursesModelCourses?>? courses;

  CoursesModel({
    this.status,
    this.errorNum,
    this.message,
    this.courses,
  });
  CoursesModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    errorNum = json['errorNum']?.toString();
    message = json['message']?.toString();
    if (json['courses'] != null) {
      final v = json['courses'];
      final arr0 = <CoursesModelCourses>[];
      v.forEach((v) {
        arr0.add(CoursesModelCourses.fromJson(v));
      });
      courses = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['errorNum'] = errorNum;
    data['message'] = message;
    if (courses != null) {
      final v = courses;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['courses'] = arr0;
    }
    return data;
  }
}
