///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LevelsModelLevelsCourses {
/*
{
  "id": 1,
  "title": "مقدمة في علم الكيمياء ",
  "desc": "التعليم الجيد و المستمر هو مفتاحك لمستقبل أفضل\nمكان واحد تقدر تتعلم فيه كل المواد و الكورسات.. \nابدأ دلوقي في المنصة.",
  "thumbnail": "assets/images/courses/test.jpg",
  "image": "assets/images/courses/test.jpg",
  "level_id": 1,
  "tags": "[\"الكيمياء\",\"أولى ثانوي\",\"الباب الاول\"]",
  "created_at": "2023-11-24T08:47:05.000000Z",
  "updated_at": "2023-11-24T08:47:05.000000Z"
}
*/

  int? id;
  String? title;
  String? desc;
  String? thumbnail;
  String? image;
  int? levelId;
  String? tags;
  String? createdAt;
  String? updatedAt;

  LevelsModelLevelsCourses({
    this.id,
    this.title,
    this.desc,
    this.thumbnail,
    this.image,
    this.levelId,
    this.tags,
    this.createdAt,
    this.updatedAt,
  });
  LevelsModelLevelsCourses.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    desc = json['desc']?.toString();
    thumbnail = json['thumbnail']?.toString();
    image = json['image']?.toString();
    levelId = json['level_id']?.toInt();
    tags = json['tags']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['desc'] = desc;
    data['thumbnail'] = thumbnail;
    data['image'] = image;
    data['level_id'] = levelId;
    data['tags'] = tags;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class LevelsModelLevels {
/*
{
  "id": 1,
  "title": "الصف الاول الثانوي",
  "order": 2,
  "courses": [
    {
      "id": 1,
      "title": "مقدمة في علم الكيمياء ",
      "desc": "التعليم الجيد و المستمر هو مفتاحك لمستقبل أفضل\nمكان واحد تقدر تتعلم فيه كل المواد و الكورسات.. \nابدأ دلوقي في المنصة.",
      "thumbnail": "assets/images/courses/test.jpg",
      "image": "assets/images/courses/test.jpg",
      "level_id": 1,
      "tags": "[\"الكيمياء\",\"أولى ثانوي\",\"الباب الاول\"]",
      "created_at": "2023-11-24T08:47:05.000000Z",
      "updated_at": "2023-11-24T08:47:05.000000Z"
    }
  ]
}
*/

  int? id;
  String? title;
  int? order;
  List<LevelsModelLevelsCourses?>? courses;

  LevelsModelLevels({
    this.id,
    this.title,
    this.order,
    this.courses,
  });
  LevelsModelLevels.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    order = json['order']?.toInt();
    if (json['courses'] != null) {
      final v = json['courses'];
      final arr0 = <LevelsModelLevelsCourses>[];
      v.forEach((v) {
        arr0.add(LevelsModelLevelsCourses.fromJson(v));
      });
      courses = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['order'] = order;
    if (courses != null) {
      final v = courses;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['courses'] = arr0;
    }
    return data;
  }
}

class LevelsModel {
/*
{
  "status": 200,
  "errorNum": "S000",
  "message": "Levels has been returned successfully",
  "levels": [
    {
      "id": 1,
      "title": "الصف الاول الثانوي",
      "order": 2,
      "courses": [
        {
          "id": 1,
          "title": "مقدمة في علم الكيمياء ",
          "desc": "التعليم الجيد و المستمر هو مفتاحك لمستقبل أفضل\nمكان واحد تقدر تتعلم فيه كل المواد و الكورسات.. \nابدأ دلوقي في المنصة.",
          "thumbnail": "assets/images/courses/test.jpg",
          "image": "assets/images/courses/test.jpg",
          "level_id": 1,
          "tags": "[\"الكيمياء\",\"أولى ثانوي\",\"الباب الاول\"]",
          "created_at": "2023-11-24T08:47:05.000000Z",
          "updated_at": "2023-11-24T08:47:05.000000Z"
        }
      ]
    }
  ]
}
*/

  int? status;
  String? errorNum;
  String? message;
  List<LevelsModelLevels?>? levels;

  LevelsModel({
    this.status,
    this.errorNum,
    this.message,
    this.levels,
  });
  LevelsModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    errorNum = json['errorNum']?.toString();
    message = json['message']?.toString();
    if (json['levels'] != null) {
      final v = json['levels'];
      final arr0 = <LevelsModelLevels>[];
      v.forEach((v) {
        arr0.add(LevelsModelLevels.fromJson(v));
      });
      levels = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['errorNum'] = errorNum;
    data['message'] = message;
    if (levels != null) {
      final v = levels;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['levels'] = arr0;
    }
    return data;
  }
}
