///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NotificationModelNotifications {
/*
{
  "title": "fdhgdjf",
  "desc": "gfdjfgdkj",
  "link": "https://youtube.com/"
}
*/

  String? title;
  String? desc;
  String? link;

  NotificationModelNotifications({
    this.title,
    this.desc,
    this.link,
  });
  NotificationModelNotifications.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    desc = json['desc']?.toString();
    link = json['link']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['desc'] = desc;
    data['link'] = link;
    return data;
  }
}

class NotificationModel {
/*
{
  "status": 200,
  "errorNum": "S000",
  "message": "Notifications have been returned successfully",
  "notifications": [
    {
      "title": "fdhgdjf",
      "desc": "gfdjfgdkj",
      "link": "https://youtube.com/"
    }
  ]
}
*/

  int? status;
  String? errorNum;
  String? message;
  List<NotificationModelNotifications?>? notifications;

  NotificationModel({
    this.status,
    this.errorNum,
    this.message,
    this.notifications,
  });
  NotificationModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    errorNum = json['errorNum']?.toString();
    message = json['message']?.toString();
    if (json['notifications'] != null) {
      final v = json['notifications'];
      final arr0 = <NotificationModelNotifications>[];
      v.forEach((v) {
        arr0.add(NotificationModelNotifications.fromJson(v));
      });
      notifications = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['errorNum'] = errorNum;
    data['message'] = message;
    if (notifications != null) {
      final v = notifications;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['notifications'] = arr0;
    }
    return data;
  }
}
