///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ParentRegisterModelDataUserStudentsPivot {
/*
{
  "parent_id": 34,
  "student_id": 1
}
*/

  int? parentId;
  int? studentId;

  ParentRegisterModelDataUserStudentsPivot({
    this.parentId,
    this.studentId,
  });
  ParentRegisterModelDataUserStudentsPivot.fromJson(Map<String, dynamic> json) {
    parentId = json['parent_id']?.toInt();
    studentId = json['student_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['parent_id'] = parentId;
    data['student_id'] = studentId;
    return data;
  }
}

class ParentRegisterModelDataUserStudents {
/*
{
  "id": 1,
  "first_name": "Omar",
  "last_name": "Abdo",
  "email": "omar@gmail.com",
  "phone": "01146127749",
  "gender": "male",
  "code": "sfsfger1",
  "image": "null",
  "level_id": 1,
  "created_at": "2023-12-10T20:20:27.000000Z",
  "updated_at": "2023-12-10T20:20:27.000000Z",
  "pivot": {
    "parent_id": 34,
    "student_id": 1
  }
}
*/

  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? phone;
  String? gender;
  String? code;
  String? image;
  int? levelId;
  String? createdAt;
  String? updatedAt;
  ParentRegisterModelDataUserStudentsPivot? pivot;

  ParentRegisterModelDataUserStudents({
    this.id,
    this.firstName,
    this.lastName,
    this.email,
    this.phone,
    this.gender,
    this.code,
    this.image,
    this.levelId,
    this.createdAt,
    this.updatedAt,
    this.pivot,
  });
  ParentRegisterModelDataUserStudents.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    gender = json['gender']?.toString();
    code = json['code']?.toString();
    image = json['image']?.toString();
    levelId = json['level_id']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    pivot = (json['pivot'] != null) ? ParentRegisterModelDataUserStudentsPivot.fromJson(json['pivot']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['email'] = email;
    data['phone'] = phone;
    data['gender'] = gender;
    data['code'] = code;
    data['image'] = image;
    data['level_id'] = levelId;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (pivot != null) {
      data['pivot'] = pivot!.toJson();
    }
    return data;
  }
}

class ParentRegisterModelDataUser {
/*
{
  "first_name": "sdf",
  "last_name": "sdf",
  "email": "1232532524dgf54@test.com",
  "gender": "male",
  "phone": "01146127749",
  "updated_at": "2024-02-04T20:15:59.000000Z",
  "created_at": "2024-02-04T20:15:59.000000Z",
  "id": 57,
  "students": [
    {
      "id": 1,
      "first_name": "Omar",
      "last_name": "Abdo",
      "email": "omar@gmail.com",
      "phone": "01146127749",
      "gender": "male",
      "code": "sfsfger1",
      "image": "null",
      "level_id": 1,
      "created_at": "2023-12-10T20:20:27.000000Z",
      "updated_at": "2023-12-10T20:20:27.000000Z",
      "pivot": {
        "parent_id": 34,
        "student_id": 1
      }
    }
  ]
}
*/

  String? firstName;
  String? lastName;
  String? email;
  String? gender;
  String? phone;
  String? updatedAt;
  String? createdAt;
  int? id;
  List<ParentRegisterModelDataUserStudents?>? students;

  ParentRegisterModelDataUser({
    this.firstName,
    this.lastName,
    this.email,
    this.gender,
    this.phone,
    this.updatedAt,
    this.createdAt,
    this.id,
    this.students,
  });
  ParentRegisterModelDataUser.fromJson(Map<String, dynamic> json) {
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    email = json['email']?.toString();
    gender = json['gender']?.toString();
    phone = json['phone']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdAt = json['created_at']?.toString();
    id = json['id']?.toInt();
    if (json['students'] != null) {
      final v = json['students'];
      final arr0 = <ParentRegisterModelDataUserStudents>[];
      v.forEach((v) {
        arr0.add(ParentRegisterModelDataUserStudents.fromJson(v));
      });
      students = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['email'] = email;
    data['gender'] = gender;
    data['phone'] = phone;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['id'] = id;
    if (students != null) {
      final v = students;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['students'] = arr0;
    }
    return data;
  }
}

class ParentRegisterModelData {
/*
{
  "user": {
    "first_name": "sdf",
    "last_name": "sdf",
    "email": "1232532524dgf54@test.com",
    "gender": "male",
    "phone": "01146127749",
    "updated_at": "2024-02-04T20:15:59.000000Z",
    "created_at": "2024-02-04T20:15:59.000000Z",
    "id": 57,
    "students": [
      {
        "id": 1,
        "first_name": "Omar",
        "last_name": "Abdo",
        "email": "omar@gmail.com",
        "phone": "01146127749",
        "gender": "male",
        "code": "sfsfger1",
        "image": "null",
        "level_id": 1,
        "created_at": "2023-12-10T20:20:27.000000Z",
        "updated_at": "2023-12-10T20:20:27.000000Z",
        "pivot": {
          "parent_id": 34,
          "student_id": 1
        }
      }
    ]
  },
  "token": "15|RFmqb7QaETjiVIHHEVqYy7axLYDuQ6At3FllaugD6c53779e"
}
*/

  ParentRegisterModelDataUser? user;
  String? token;

  ParentRegisterModelData({
    this.user,
    this.token,
  });
  ParentRegisterModelData.fromJson(Map<String, dynamic> json) {
    user = (json['user'] != null) ? ParentRegisterModelDataUser.fromJson(json['user']) : null;
    token = json['token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['token'] = token;
    return data;
  }
}

class ParentRegisterModel {
/*
{
  "status": 200,
  "errorNum": "S000",
  "message": "Registered Successfully",
  "data": {
    "user": {
      "first_name": "sdf",
      "last_name": "sdf",
      "email": "1232532524dgf54@test.com",
      "gender": "male",
      "phone": "01146127749",
      "updated_at": "2024-02-04T20:15:59.000000Z",
      "created_at": "2024-02-04T20:15:59.000000Z",
      "id": 57,
      "students": [
        {
          "id": 1,
          "first_name": "Omar",
          "last_name": "Abdo",
          "email": "omar@gmail.com",
          "phone": "01146127749",
          "gender": "male",
          "code": "sfsfger1",
          "image": "null",
          "level_id": 1,
          "created_at": "2023-12-10T20:20:27.000000Z",
          "updated_at": "2023-12-10T20:20:27.000000Z",
          "pivot": {
            "parent_id": 34,
            "student_id": 1
          }
        }
      ]
    },
    "token": "15|RFmqb7QaETjiVIHHEVqYy7axLYDuQ6At3FllaugD6c53779e"
  }
}
*/

  int? status;
  String? errorNum;
  String? message;
  ParentRegisterModelData? data;

  ParentRegisterModel({
    this.status,
    this.errorNum,
    this.message,
    this.data,
  });
  ParentRegisterModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    errorNum = json['errorNum']?.toString();
    message = json['message']?.toString();
    data = (json['data'] != null) ? ParentRegisterModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['errorNum'] = errorNum;
    data['message'] = message;
    data['data'] = this.data!.toJson();
      return data;
  }
}
