///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ParentGetStudentsModelParentStudentsPivot {
/*
{
  "parent_id": 34,
  "student_id": 1
}
*/

  int? parentId;
  int? studentId;

  ParentGetStudentsModelParentStudentsPivot({
    this.parentId,
    this.studentId,
  });
  ParentGetStudentsModelParentStudentsPivot.fromJson(Map<String, dynamic> json) {
    parentId = json['parent_id']?.toInt();
    studentId = json['student_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['parent_id'] = parentId;
    data['student_id'] = studentId;
    return data;
  }
}

class ParentGetStudentsModelParentStudents {
/*
{
  "id": 1,
  "first_name": "Omar",
  "last_name": "Abdo",
  "email": "omar@gmail.com",
  "phone": "01146127749",
  "gender": "male",
  "code": "sfsfger1",
  "image": null,
  "level_id": null,
  "created_at": "2023-12-10T20:20:27.000000Z",
  "updated_at": "2023-12-10T20:20:27.000000Z",
  "pivot": {
    "parent_id": 34,
    "student_id": 1
  }
}
*/

  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? phone;
  String? gender;
  String? code;
  String? image;
  String? levelId;
  String? createdAt;
  String? updatedAt;
  ParentGetStudentsModelParentStudentsPivot? pivot;

  ParentGetStudentsModelParentStudents({
    this.id,
    this.firstName,
    this.lastName,
    this.email,
    this.phone,
    this.gender,
    this.code,
    this.image,
    this.levelId,
    this.createdAt,
    this.updatedAt,
    this.pivot,
  });
  ParentGetStudentsModelParentStudents.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    gender = json['gender']?.toString();
    code = json['code']?.toString();
    image = json['image']?.toString();
    levelId = json['level_id']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    pivot = (json['pivot'] != null) ? ParentGetStudentsModelParentStudentsPivot.fromJson(json['pivot']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['email'] = email;
    data['phone'] = phone;
    data['gender'] = gender;
    data['code'] = code;
    data['image'] = image;
    data['level_id'] = levelId;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (pivot != null) {
      data['pivot'] = pivot!.toJson();
    }
    return data;
  }
}

class ParentGetStudentsModel {
/*
{
  "status": 200,
  "errorNum": "S000",
  "message": "Student has been added successfully",
  "parent_students": [
    {
      "id": 1,
      "first_name": "Omar",
      "last_name": "Abdo",
      "email": "omar@gmail.com",
      "phone": "01146127749",
      "gender": "male",
      "code": "sfsfger1",
      "image": null,
      "level_id": null,
      "created_at": "2023-12-10T20:20:27.000000Z",
      "updated_at": "2023-12-10T20:20:27.000000Z",
      "pivot": {
        "parent_id": 34,
        "student_id": 1
      }
    }
  ]
}
*/

  int? status;
  String? errorNum;
  String? message;
  List<ParentGetStudentsModelParentStudents?>? parentStudents;

  ParentGetStudentsModel({
    this.status,
    this.errorNum,
    this.message,
    this.parentStudents,
  });
  ParentGetStudentsModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    errorNum = json['errorNum']?.toString();
    message = json['message']?.toString();
    if (json['parent_students'] != null) {
      final v = json['parent_students'];
      final arr0 = <ParentGetStudentsModelParentStudents>[];
      v.forEach((v) {
        arr0.add(ParentGetStudentsModelParentStudents.fromJson(v));
      });
      parentStudents = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['errorNum'] = errorNum;
    data['message'] = message;
    if (parentStudents != null) {
      final v = parentStudents;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['parent_students'] = arr0;
    }
    return data;
  }
}
