///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProfileModelProfile {
/*
{
  "id": 53,
  "first_name": "sdf",
  "last_name": "sdf",
  "email": "omar@student.test",
  "email_verified_at": "null",
  "phone": "01146127749",
  "gender": "male",
  "image": "null",
  "code": "RRZB00",
  "status": 1,
  "level_id": 1,
  "role": "student",
  "created_at": "2024-02-03T16:13:00.000000Z",
  "updated_at": "2024-02-03T16:13:00.000000Z"
}
*/

  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? emailVerifiedAt;
  String? phone;
  String? gender;
  String? image;
  String? code;
  int? status;
  int? levelId;
  String? role;
  String? createdAt;
  String? updatedAt;

  ProfileModelProfile({
    this.id,
    this.firstName,
    this.lastName,
    this.email,
    this.emailVerifiedAt,
    this.phone,
    this.gender,
    this.image,
    this.code,
    this.status,
    this.levelId,
    this.role,
    this.createdAt,
    this.updatedAt,
  });
  ProfileModelProfile.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    email = json['email']?.toString();
    emailVerifiedAt = json['email_verified_at']?.toString();
    phone = json['phone']?.toString();
    gender = json['gender']?.toString();
    image = json['image']?.toString();
    code = json['code']?.toString();
    status = json['status']?.toInt();
    levelId = json['level_id']?.toInt();
    role = json['role']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['email'] = email;
    data['email_verified_at'] = emailVerifiedAt;
    data['phone'] = phone;
    data['gender'] = gender;
    data['image'] = image;
    data['code'] = code;
    data['status'] = status;
    data['level_id'] = levelId;
    data['role'] = role;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class ProfileModel {
/*
{
  "status": 200,
  "errorNum": "S000",
  "message": "profile has been returned successfully",
  "profile": {
    "id": 53,
    "first_name": "sdf",
    "last_name": "sdf",
    "email": "omar@student.test",
    "email_verified_at": "null",
    "phone": "01146127749",
    "gender": "male",
    "image": "null",
    "code": "RRZB00",
    "status": 1,
    "level_id": 1,
    "role": "student",
    "created_at": "2024-02-03T16:13:00.000000Z",
    "updated_at": "2024-02-03T16:13:00.000000Z"
  }
}
*/

  int? status;
  String? errorNum;
  String? message;
  ProfileModelProfile? profile;

  ProfileModel({
    this.status,
    this.errorNum,
    this.message,
    this.profile,
  });
  ProfileModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    errorNum = json['errorNum']?.toString();
    message = json['message']?.toString();
    profile = (json['profile'] != null) ? ProfileModelProfile.fromJson(json['profile']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['errorNum'] = errorNum;
    data['message'] = message;
    if (profile != null) {
      data['profile'] = profile!.toJson();
    }
    return data;
  }
}
