///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class QuizsDegreesModelStudentQuizzes {
/*
{
  "title": "Fk3153",
  "degree": 134,
  "grade": 84,
  "quiz_duration": "10:47:26"
}
*/

  String? title;
  int? degree;
  int? grade;
  String? quizDuration;

  QuizsDegreesModelStudentQuizzes({
    this.title,
    this.degree,
    this.grade,
    this.quizDuration,
  });
  QuizsDegreesModelStudentQuizzes.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    degree = json['degree']?.toInt();
    grade = json['grade']?.toInt();
    quizDuration = json['quiz_duration']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['degree'] = degree;
    data['grade'] = grade;
    data['quiz_duration'] = quizDuration;
    return data;
  }
}

class QuizsDegreesModel {
/*
{
  "status": 200,
  "errorNum": "S000",
  "message": "Student 1 quizzes detials has been returned successfully",
  "student_quizzes": [
    {
      "title": "Fk3153",
      "degree": 134,
      "grade": 84,
      "quiz_duration": "10:47:26"
    }
  ]
}
*/

  int? status;
  String? errorNum;
  String? message;
  List<QuizsDegreesModelStudentQuizzes?>? studentQuizzes;

  QuizsDegreesModel({
    this.status,
    this.errorNum,
    this.message,
    this.studentQuizzes,
  });
  QuizsDegreesModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    errorNum = json['errorNum']?.toString();
    message = json['message']?.toString();
    if (json['student_quizzes'] != null) {
      final v = json['student_quizzes'];
      final arr0 = <QuizsDegreesModelStudentQuizzes>[];
      v.forEach((v) {
        arr0.add(QuizsDegreesModelStudentQuizzes.fromJson(v));
      });
      studentQuizzes = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['errorNum'] = errorNum;
    data['message'] = message;
    if (studentQuizzes != null) {
      final v = studentQuizzes;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['student_quizzes'] = arr0;
    }
    return data;
  }
}
