///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class StudentRegisterModelUserDataUserLevel {
/*
{
  "id": 1,
  "title": "الصف الاول الاعدادي",
  "order": 1,
  "image": "assets/images/banners/level1.jpg"
}
*/

  int? id;
  String? title;
  int? order;
  String? image;

  StudentRegisterModelUserDataUserLevel({
    this.id,
    this.title,
    this.order,
    this.image,
  });
  StudentRegisterModelUserDataUserLevel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    order = json['order']?.toInt();
    image = json['image']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['order'] = order;
    data['image'] = image;
    return data;
  }
}

class StudentRegisterModelUserDataUser {
/*
{
  "first_name": "sdf",
  "last_name": "sdf",
  "email": "sd1f10@gmail.com",
  "gender": "male",
  "phone": "01146127749",
  "level_id": "1",
  "code": "cAfv07",
  "updated_at": "2024-02-02T18:25:08.000000Z",
  "created_at": "2024-02-02T18:25:08.000000Z",
  "id": 55,
  "level_title": "الصف الاول الاعدادي",
  "level": {
    "id": 1,
    "title": "الصف الاول الاعدادي",
    "order": 1,
    "image": "assets/images/banners/level1.jpg"
  }
}
*/

  String? firstName;
  String? lastName;
  String? email;
  String? gender;
  String? phone;
  String? levelId;
  String? code;
  String? updatedAt;
  String? createdAt;
  int? id;
  String? levelTitle;
  StudentRegisterModelUserDataUserLevel? level;

  StudentRegisterModelUserDataUser({
    this.firstName,
    this.lastName,
    this.email,
    this.gender,
    this.phone,
    this.levelId,
    this.code,
    this.updatedAt,
    this.createdAt,
    this.id,
    this.levelTitle,
    this.level,
  });
  StudentRegisterModelUserDataUser.fromJson(Map<String, dynamic> json) {
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    email = json['email']?.toString();
    gender = json['gender']?.toString();
    phone = json['phone']?.toString();
    levelId = json['level_id']?.toString();
    code = json['code']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdAt = json['created_at']?.toString();
    id = json['id']?.toInt();
    levelTitle = json['level_title']?.toString();
    level = (json['level'] != null) ? StudentRegisterModelUserDataUserLevel.fromJson(json['level']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['email'] = email;
    data['gender'] = gender;
    data['phone'] = phone;
    data['level_id'] = levelId;
    data['code'] = code;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['id'] = id;
    data['level_title'] = levelTitle;
    if (level != null) {
      data['level'] = level!.toJson();
    }
    return data;
  }
}

class StudentRegisterModelUserData {
/*
{
  "user": {
    "first_name": "sdf",
    "last_name": "sdf",
    "email": "sd1f10@gmail.com",
    "gender": "male",
    "phone": "01146127749",
    "level_id": "1",
    "code": "cAfv07",
    "updated_at": "2024-02-02T18:25:08.000000Z",
    "created_at": "2024-02-02T18:25:08.000000Z",
    "id": 55,
    "level_title": "الصف الاول الاعدادي",
    "level": {
      "id": 1,
      "title": "الصف الاول الاعدادي",
      "order": 1,
      "image": "assets/images/banners/level1.jpg"
    }
  },
  "token": "4|EhRTJW1RXCy6NJKgDPf4cQG8yYqDTJgicXPCpnju89924bd2"
}
*/

  StudentRegisterModelUserDataUser? user;
  String? token;

  StudentRegisterModelUserData({
    this.user,
    this.token,
  });
  StudentRegisterModelUserData.fromJson(Map<String, dynamic> json) {
    user = (json['user'] != null) ? StudentRegisterModelUserDataUser.fromJson(json['user']) : null;
    token = json['token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['token'] = token;
    return data;
  }
}

class StudentRegisterModel {
/*
{
  "status": 200,
  "errorNum": "S000",
  "message": "Registered Successfully",
  "user_data": {
    "user": {
      "first_name": "sdf",
      "last_name": "sdf",
      "email": "sd1f10@gmail.com",
      "gender": "male",
      "phone": "01146127749",
      "level_id": "1",
      "code": "cAfv07",
      "updated_at": "2024-02-02T18:25:08.000000Z",
      "created_at": "2024-02-02T18:25:08.000000Z",
      "id": 55,
      "level_title": "الصف الاول الاعدادي",
      "level": {
        "id": 1,
        "title": "الصف الاول الاعدادي",
        "order": 1,
        "image": "assets/images/banners/level1.jpg"
      }
    },
    "token": "4|EhRTJW1RXCy6NJKgDPf4cQG8yYqDTJgicXPCpnju89924bd2"
  }
}
*/

  int? status;
  String? errorNum;
  String? message;
  StudentRegisterModelUserData? userData;

  StudentRegisterModel({
    this.status,
    this.errorNum,
    this.message,
    this.userData,
  });
  StudentRegisterModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    errorNum = json['errorNum']?.toString();
    message = json['message']?.toString();
    userData = (json['user_data'] != null) ? StudentRegisterModelUserData.fromJson(json['user_data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['errorNum'] = errorNum;
    data['message'] = message;
    if (userData != null) {
      data['user_data'] = userData!.toJson();
    }
    return data;
  }
}
